### ISSUE TITLE
How about use image-file-name-extensions instead of auto-img-extensions

### ISSUE THREAD

**Issue by lujun9972** [tashrifsanil/org-easy-img-insert#2]
image-file-name-extensions is a variable defined in `image-file.el'.
It already defined a list of image-file filename extensions.

**Comment by my7h3le** [comment]
Thanks for the feedback, and I'm glad you checked out the package. I've made the changes you said and it's on this [commit](https://github.com/tashrifsanil/auto-img-link-insert/commit/dc804bc7d3437b3faf2218158427d0ff38e46254)
