### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by alphapapa** [tashrifsanil/org-easy-img-insert#4]
Hi there, I saw this package in Sacha's review.  It looks interesting.  Here are a few suggestions for improvements:
1.  The readme/description doesn't make it clear what exactly is inserted.  From looking at the code, it appears that the image is downloaded into a newly created directory.
2.  It would be a good idea to allow configuration of the directory and such.  Some users might prefer to put the images into the same directory as the org file, while others might want to put them in a subdirectory with a certain name.
3.  I saw a lot of nested `let` statements.  May I recommend `let*`?  ;)
4.  I also recommend the f.el package.  It's better than rolling your own filename/directory functions.
5.  It's good that you added docstrings to all the functions.  I recommend following the Emacs conventions, meaning to remove the "takes X as args" parts and the parentheses around the arg names.
6.  I think the way you're getting the image extension is not good.  Getting it from a URL like that (I looked at the MELPA pull request, where you give an example of a URL with an encoded redirect) is failure-prone: you might get the wrong extension if the URL were messy.  A better way would be to simply download the file using the filename returned by the server, and then get the extension from the file on disk.  It would be much more reliable.
7.  Another issue is that people might often not want to change the image filename in the first place, so making the user type it in could be a hassle.  It would probably be better to simply use the filename given by the server.  If the user wants to change the filename, it would be handy to be able to call your function with a prefix arg, and then you could offer the user the chance to rename the file before inserting it.
8.  One other thing, which is probably the most significant: your package doesn't have "org" in the name, so there's no indication that it's related to org-mode.  It would be better to call it something like `org-easy-insert-image` so that people can find it when looking for org-related packages.

**Comment by my7h3le** [comment]
Thanks, for checking the package out, and thanks for the suggestions. I will probably fix these issues later on in the day or by tomorrow. Your right about the nested 'let' statements, I thought there has to be a better way, but at that time I just left it as it is.

Also would you want to be able to choose the directory that the image gets downloaded to in the mini buffer itself?. I initially avoided this cause I felt like it would be too many options.

Also feel free, to fork and make pull requests 😊

**Comment by my7h3le** [comment]
On your 6th note

>  I think the way you're getting the image extension is not good. Getting it from a URL like that (I looked at the MELPA pull request, where you give an example of a URL with an encoded redirect) is failure-prone: you might get the wrong extension if the URL were messy. A better way would be to simply download the file using the filename returned by the server, and then get the extension from the file on disk. It would be much more reliable.

The reason why I extract the file name from the URL is so that I can create a filename for it so that `wget` can save the download file as such. The problem is if you don't specify a filename to `wget` it will download the image and save it as the link name, so that doesn't really help

For your 8th note, I definitely had second thoughts about the name of the package. The name change however will take a while to make it's way upstream

**Comment by alphapapa** [comment]
> Also would you want to be able to choose the directory that the image gets downloaded to in the mini buffer itself?. I initially avoided this cause I felt like it would be too many options.

I guess that could be helpful sometimes.  Maybe you could use a prefix arg to activate that feature.

> The reason why I extract the file name from the URL is so that I can create a filename for it so that wget can save the download file as such. The problem is if you don't specify a filename to wget it will download the image and save it as the link name, so that doesn't really help

Hm, well, I think there are a few issues here:
1.  In the case of redirect URLs, the redirect should be followed first, and that will likely simplify the process of getting the filename from the URL.
2.  Sometimes the server will offer a filename in the `Content-Disposition` HTTP headers.  If not, then it should be clear from the final URL.  However, even then, an extension is not guaranteed to be present in the filename.  So you could use the `file` command to get the filetype, or just leave it without an extension.
3.  There are Emacs functions to download files and such, so you don't need to use external commands like wget.

Just some ideas.  :)

**Comment by tashrifsanil** [comment]
> There are Emacs functions to download files and such, so you don't need to use external commands like wget.

Really? I only used wget because I couldn't find any emacs function equivalent. Do you know any emacs function that does just that?
